name: Seed starter issues
on:
  create: {}
  push:
    branches: [main]
    paths: [.github/seed-issues/**]

jobs:
  seed:
    if: ${{ github.event_name == 'create' || github.run_number == 1 }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Create issues from YAML
        run: |
          python - <<'PY'
          import os, yaml, requests
          with open('.github/seed-issues/issues.yml', encoding='utf-8') as f:
              items = yaml.safe_load(f)
          token = os.environ['GITHUB_TOKEN']
          owner, repo = os.environ['GITHUB_REPOSITORY'].split('/')
          url = f'https://api.github.com/repos/{owner}/{repo}/issues'
          headers = {'Authorization': f'Bearer {token}',
                     'Accept': 'application/vnd.github+json'}
          for it in items:
              data = {'title': it['title'], 'body': it.get('body',''),
                      'labels': it.get('labels', [])}
              r = requests.post(url, json=data, headers=headers)
              r.raise_for_status()
          PY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
